# Generated by Django 3.1.2 on 2021-05-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
